In [10]:
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
import numpy as np


bikes = pd.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/bikes.csv')
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112475 entries, 0 to 112474
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   dteday        112475 non-null  object
 1   hr            112475 non-null  float64
 2   casual        112475 non-null  int64
 3   registered    112475 non-null  int64
 4   temp_c        112475 non-null  float64
 5   feels_like_c  112475 non-null  float64
 6   hum           112475 non-null  float64
 7   windspeed     112475 non-null  float64
 8   weathersit    112475 non-null  int64
 9   season        112475 non-null  int64
 10  holiday       112475 non-null  int64
 11  workingday    112475 non-null  int64
dtypes: float64(5), int64(6), object(1)
memory usage: 10.3+ MB

In [11]:
bikes.head()

,dteday,hr,casual,registered,temp_c,feels_like_c,hum,windspeed,weathersit,season,holiday,workingday
0,1/1/2011,0.0,3,13,3.0,3.0,0.7957,0.8,1,1,0,0
1,1/1/2011,1.0,8,30,1.7,1.7,0.8272,0.8,1,1,0,0
2,1/1/2011,2.0,5,26,1.9,1.9,0.8157,1.1,1,1,0,0
3,1/1/2011,3.0,3,9,2.5,2.5,0.7831,0.8,1,1,0,0
4,1/1/2011,4.0,0,1,2.0,2.0,0.8075,1.1,1,1,0,0

In [12]:
#clean date
bikes["dteday"] = pd.to_datetime(bikes["dteday"])
bikes["year"] = bikes["dteday"].dt.year
bikes["month"] = bikes["dteday"].dt.month
bikes["day_of_week"] = bikes["dteday"].dt.dayofweek

#cyclical encoding
bikes["hr_sin"] = np.sin(2 * np.pi * bikes["hr"] / 24)
bikes["hr_cos"] = np.cos(2 * np.pi * bikes["hr"] / 24)

#make target
bikes["count"] = bikes["casual"] + bikes["registered"]

# drop extra columns
bikes = bikes.drop(columns=["dteday", "temp_c", "hr", "casual", "registered"])

# Hot encode
bikes = pd.get_dummies(bikes, columns=["weathersit", "season"], drop_first=True)

In [13]:
bikes.head()

,feels_like_c,hum,windspeed,holiday,workingday,year,month,day_of_week,hr_sin,hr_cos,count,weathersit_2,weathersit_3,weathersit_4,season_2,season_3,season_4
0,3.0,0.7957,0.8,0,0,2011,1,5,0.000000,1.000000,16,False,False,False,False,False,False
1,1.7,0.8272,0.8,0,0,2011,1,5,0.258819,0.965926,38,False,False,False,False,False,False
2,1.9,0.8157,1.1,0,0,2011,1,5,0.500000,0.866025,31,False,False,False,False,False,False
3,2.5,0.7831,0.8,0,0,2011,1,5,0.707107,0.707107,12,False,False,False,False,False,False
4,2.0,0.8075,1.1,0,0,2011,1,5,0.866025,0.500000,1,False,False,False,False,False,False